<?php

/**
 * @file
 * Cavalla_blog module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function cavalla_blog_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.cavalla_blog':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_theme().
 * Lets us define our node templates in this module.
 */
function cavalla_blog_theme($existing, $type, $theme, $path) {
  return [
    'node__cavalla_blog' => [
      'base hook' => 'node',
    ],

    // Cavalla Popular Post.
    'paragraph__cavalla_blog_popular_post' => [
      'base hook' => 'paragraph',
    ],
    // Cavalla Recent Post.
    'paragraph__cavalla_blog_recent_post' => [
      'base hook' => 'paragraph',
    ],

    // Cavalla Reccommeded Post.
    'paragraph__cavalla_blog_reccomened_post' => [
      'base hook' => 'paragraph',
    ],
  ];
}
