<?php

/**
 * @file
 * Cavalla_call_to_action module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function cavalla_call_to_action_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.cavalla_call_to_action':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_theme().
 * Lets us define our paragraphs templates in this module.
 */
function cavalla_call_to_action_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__cavalla_call_to_action' => [
      'base hook' => 'paragraph',
    ],

  ];
}

/**
 *
 */
function cavalla_call_to_action_preprocess_paragraph__cavalla_call_to_action(&$variables) {
  $paragraph = $variables['elements']['#paragraph'];

  if ($paragraph->get('field_cavalla_call_to_action_vw')->value == '1') {
    $half_view_display = 'half_view ';
  }

  if ($paragraph->get('field_cavalla_cta_overlay')->value == '1') {
    $overlay = 'overlay ';
  }

  $variables['cta_logo'] = $paragraph->get('field_cavalla_cta_logo')->value;
  $variables['attributes']['class'] = 'call_to_action_bundle ' . $overlay . $half_view_display;

}